export const TOKEN_STORAGE_KEY = "GLOBIE_ACCESS_TOKEN";
export const USER_ROLE_STORAGE_KEY = "GLOBIE_USER_ROLE";
export const STORE_INFO_STORAGE_KEY = "GLOBIE_STORE";
export const PAYMENT_METHOD = {
  ELECTRONIC_PAYMENT: "ELECTRONIC_PAYMENT",
  CASH_ON_DELIVERY: "CASH_ON_DELIVERY",
};
